version: '3.9'

services:
  mongodb:
    restart: on-failure:3
    image: mongo:7.0.0
    container_name: mongodb-container
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: restaurant-manager
    volumes:
      - ./docker/db:/data/db
    ports:
      - "27017:27017"

volumes:
  mongodb-data:
