version: '3.9'

services:
  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    container_name: my-mongodb-container
    environment:
      MONGO_INITDB_ROOT_USERNAME: myadmin
      MONGO_INITDB_ROOT_PASSWORD: mysecretpassword
      MONGO_INITDB_DATABASE: mydatabase
    volumes:
      - ./docker/db:/data/db
    ports:
      - "27017:27017"

volumes:
  mongodb-data: